# Site settings
title: Frederick Silva
email: devfrederick@gmail.com
description: > # Creative Developer developer, doctor, entrepreneur
  Sou apaixonado por design e desenvolvimento, encontrei no frontend uma forma de unir todas as minhas paix√µes
  e me divirto trabalhando.
url: "http://fredericksilva.github.io" 
twitter_username: fredericksilva
github_username:  fredericksilva
linkidin_username: frederickinrio
instagram_username: fredericksilva

# Build settings
markdown: kramdown
